### ISSUE TITLE
How to use "update" from exe?

### ISSUE THREAD

**Issue by g4269159** [Liru/tumblr-downloader#14]
I don't know anything about command lines or stuff. Can I update with -u from the download.txt? I don't want to redownload the entire blog.

**Comment by Liru** [comment]
Two possibly related things:

1. The current version, 1.3.0, has a slight bug that will cause it to redownload everything. Even the non-update mode shouldn't do that. The intended non-update behaviour is to check the entire blog (not really too bandwidth-intensive) and only download the stuff that wasn't found. It's fixed in the 1.3.1 release.

2. The "update" behaviour will be the default from 1.4.0 on, only doing a full scrape if it is explicitly commanded, or if a new version is put in its place.

----

That being said, if you have a modern version of Windows...

1. Go to the directory where you have the executable.
2. Hold `shift` and right-click somewhere in the folder.
3. Choose the "Open command window here" option.
4. Type in `tumblr-downloader.exe -u` and press enter to run it in update mode. Alternatively, type `tumblr-downloader.exe -h` to show all the different options you can add on.

This is from memory, so I'm not sure if it'll work, but it should. Tell me if it does.

**Comment by g4269159** [comment]
Thank you, the command line worked!
