### ISSUE TITLE
Updated video downloads

### ISSUE THREAD

**Issue by ecks12** [Liru/tumblr-downloader#15]
Will there be an update for videos. Older videos will download, but newer ones will not.

**Comment by Liru** [comment]
Can you provide an example of a post with a newer video?

**Comment by ecks12** [comment]
For example, I downloaded videos from this page: canadianmixedcouple519.tumblr.com
It didn't download any videos after january 7th.

**Comment by Liru** [comment]
Found the problem. I forgot to properly check for a trailing resolution, or in this case, a lack of one. Since the URLs didn't have them, they weren't detected as videos. Stupid oversight on my part.

Currently testing. If it works, the change should be pushed very shortly. A new version will be released in ~10 hours since I don't have access to my build machine at the moment.
