### ISSUE TITLE
Change names of WebM/Gfycat files

### ISSUE THREAD

**Issue by PapiRus01** [Liru/tumblr-downloader#19]
I was wondering if it is possible to get videos from gfycat named in the same manner as pictures and gifs from tumblr? Keeping original file names just ruins order in which files are placed in folder and viewed in players / browsers.

**Comment by Liru** [comment]
The problem is that I don't know Tumblr's URL generation scheme, so I can't use something like a post ID to directly derive something that looks like a tumblr URL without causing a lot of problems in the future.

There is the possibility of tracking the previous files that have been parsed and trying to generate something from that, but that gets buggy really quickly based on corner cases (what if a GFY is the first post on a tumblr? What if there are several posts with GFY files in a row? What if another image in another post has that same URL? et c.)

Alternatively, something easier to do (but non-foolproof) would be to find any other downloadables (images, videos, et c) on the page and rename the GFY to something similar to the other posts. For instance, if it finds a file named `tumblr_somethingo1_500.gif`, it could rename the GFY to `tumblr_somethingo1_gfycat.mp4` once it's downloaded. This also has the advantage of being futureproof, keeping the URL intact without having the possibility to clash with a randomly-generated URL found in another post. If no other file is found in the post, defaulting to the standard Gfycat name could probably work.

What do you think?

**Comment by PapiRus01** [comment]
I see. I am now using a method you mentioned  here. Only problem is that with many gfycat files in the blog it takes some time to rename them. It wold be great to have some other option. Thank you anyway.

**Comment by Liru** [comment]
Yes, that's why I'm asking you which method you would prefer for the program to use.

Do the posts that you download the Gfycat files from tend to have a preview image on them?

**Comment by PapiRus01** [comment]
Yes. Gfycat files have gif and sometimes jpeg previews. In some cases one preview image is followed by more than one video (for example 360p and 720p option). I couldn't really find gfycat link without a preview image. Guess If video file had the name of previously downloaded image (or maybe one generated from it) then the order of files would be almost completely restored. Some manual corrections might have to be made, but the whole process would be very much easier.
