### ISSUE TITLE
Option to drop the /downloads/ sub-folder

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#2]
Great command-line app, very easy to schedule to run every day! Thanks a lot for creating it!

I would prefer to have my user folders directly in the main folder, without /downloads/

I see no real reason for one level deeper hierarchy.

Thanks!

**Comment by Liru** [comment]
I've been thinking about this for a while, since I got a lot of suggestions from others about this as well. I keep it like this since it's slightly easier to develop with, and a bit more future-proof, but I can see why it could be better like this for another end user.

I still need to think about it a bit more, though. It'll probably be changed in the next few days.

**Comment by apoapostolov** [comment]
Thanks for considering my suggestion!
