### ISSUE TITLE
Configurable file name template per blog. 

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#24]
This is an enhancement request on top of #22 and #23 since I would prefer this per blog. 

Please add the ability to define a filename template for each blog with following building blocks
* Blog Name
* Post Name
* Post Date
* Original Name/Number (currently used)
* etc.

For example on Blog "Kitten's Den" the post "My Kitten" and template [Blog Name][Post Name][Original Name] would generate a file named, for example, Kittens-Den-My-Kitten-343h34f-1.png

This would need name normalization, max characters per tag, etc. but result in a lot more readable and even searchable outputs.

**Comment by Liru** [comment]
I'm against this for two reasons, off the top of my head.

1. While it would be relatively cool to have something like this, it would be a bit difficult to implement, mostly due to varying templates. There's a lot of edge cases to consider, as well. If it was implemented, the main focus would have to be invariable blocks for something like this, and the only two I can think of right now are the blog name and original name. This is already done with the directory structure.

2. It complicates duplicate detection, due to race conditions and reblogs. What if someone reblogged an old post of theirs with additional comments? The current system would detect it as a duplicate image and move on. The template system would require either a full-on database or key-value storage to keep track of original filenames (which is unwieldy for multiple reasons), require scanning the entire blog each time a download is called (which wastes bandwidth and time), or just download it (which takes up space for no good reason).

I could just mark this as `wontfix` and move on, but I do see its use. Hm. Will think about it a bit more.
