### ISSUE TITLE
Hardlink duplicate files

### ISSUE THREAD

**Issue by Liru** [Liru/tumblr-downloader#29]
Hardlinking duplicate files would solve a lot of issues regarding duplicate detection, where to put files, and the like.

The only problems here would be a linear increase in memory usage to keep track of the files downloaded, and the typical drawbacks of hardlinking: changing one file would change them all.

**Comment by apoapostolov** [comment]
How would hardlinking work if files were uploaded and then downloaded from
a cloud storage?

**Comment by Liru** [comment]
They'd probably be treated as different files? I'm not sure how different cloud providers handle hardlinked files. Most would deduplicate it on their end since it's the same file, but they would likely be redownloaded as two different files.

**Comment by apoapostolov** [comment]
The uncertainty scares me a little, I would definitely prefer #25 but it is ultimately up to you.

I use cloud storage to hold on my downloaded Tumblr archives a lot, especially those no more active, since I download massive hundreds of gigabytes of content. If the cloud storage is choked or skips content because of use of hardlinks it is not meant to handle, then I cannot benefit from this improvement.

**Comment by Liru** [comment]
Again, it depends on what you use for storage. If you can use `rsync` or `tar` or a bunch of other tools, you should be fine.
