### ISSUE TITLE
Please return support for command line parameters dropped in 1.5

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#33]
In 1.5 most command line parameters were dropped in favor of a config file. Unfortunately this took away the capability to support multiple command line configurations saving different type of contents (images vs. videos, for example) into different main directory.  Now I have to support a totally separate installation of Tumblr Downloader if I want to have the old functionality. Is there a reason why command line params like -dir are incompatible as an override to the default config file?

**Comment by Liru** [comment]
> Is there a reason why command line params like -dir are incompatible as an override to the default config file?

Mostly laziness, with a bit of looking forward. Go's standard `flag` library has behaviour at initialization that makes zero sense, making a feature like "override this parameter via the command line" not as simple as it should be. I didn't feel like getting around that at the time since I was busy with other things.

It's also likely to be removed completely and replaced with settings in the `download` file itself for each user/group of users.

Will look into fixing it when I have time, probably for v1.5.1.

**Comment by apoapostolov** [comment]
Thank you. I do not wish to dictate you how to resolve this, I think there are multiple options here:
* Return command line parameters support
* Add functionality to supply alternative config files via command line - much cleaner since saves writing heavy command lines, and in future the config file content may grow, making very long command lines not viable.
