### ISSUE TITLE
Can't download some blog

### ISSUE THREAD

**Issue by potato93** [Liru/tumblr-downloader#37]
If 'Allow logged-out users to see this blog(blog privacy setting)' is off, can't download file.

**Comment by Liru** [comment]
Mostly working as intended. Login functionality was relatively complex to implement and lacked anonymity. Also, it would require people setting API keys in the command line, which is a bit complex for what I wanted. It was put on the backburner, since not many blogs I know have that enabled.

I may work on it someday, but I don't foresee it happening, to be honest.

**Comment by apoapostolov** [comment]
Hello Liru, API doesn't need to be supplied on command line now that we have settings file.
