### ISSUE TITLE
Optional minimized/silent launch

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#4]
Is there a way to launch the app in a silent mode without the UI showing on-screen?

**Comment by Liru** [comment]
Currently, there isn't a way to do that, as the UI the program uses is the default OS shell. If I decide on adding a GUI later on, then that will be one of the first things added.

If you're on Linux/Mac, adding an ` &` after the command will launch it "silently".

If you're on Windows, [here's a solution](http://serverfault.com/a/9039). Copy the following into a `.vbs` file and run that instead of the main .exe:

```vbs
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "tumblr-downloader.exe" & Chr(34), 0
Set WinScriptHost = Nothing
```

Save that in the same directory as the exe, and run that. That should get it to launch silently for now.
