### ISSUE TITLE
Use raw URLs

### ISSUE THREAD

**Issue by Liru** [Liru/tumblr-downloader#61]
Apparently, tumblr has a size bigger than 1280, and it's `raw`. Update the downloader so that it tries those first.

* [ ] Change `xx.media` to `s3.amazonaws.com/data`
* [ ] Replace the resolution number with `raw` (ie, `tumblr_p244atnHUp1qln62zo2_1280.jpg` to `tumblr_p244atnHUp1qln62zo2_raw.jpg`
* [ ] Fall back to the standard URL if the raw URL doesn't exist for some reason

**Comment by UMLAUTaxl** [comment]
hey, thanks for your app.
according to this the link might change some more: 
https://www.reddit.com/r/userscripts/comments/6qct3b/use_tumblr_raw_image/

and i also found some raws that have a smaller resolution than the 1280 ... these were all drawn images though. so you might have to add an option instead of just changing the code please.

**Comment by Liru** [comment]
Closing for now, as tumblr removed the raw image workaround a while back.
